name: Debug

on:
  push:
    branches:
      - '*'

concurrency: ${{ github.workflow }}-${{ github.ref }}


jobs:
  debug:
    name: debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Debug workflow variables
        run: |
          echo github.workflow = ${{ github.workflow }}
          echo github.ref = ${{ github.ref }}
          echo github.action = ${{ github.action }}
          echo github.action_path = ${{ github.action_path }}
          echo github.action_ref = ${{ github.action_ref }}
          echo github.action_repository = ${{ github.action_repository }}
          echo github.action_status = ${{ github.action_status }}
          echo github.actor = ${{ github.actor }}
          echo github.actor_id = ${{ github.actor_id }}
          echo github.base_ref = ${{ github.base_ref }}
          echo github.env = ${{ github.env }}
          echo github.ref_name = ${{ github.ref_name }}
          echo github.ref_protected = ${{ github.ref_protected }}
          echo github.repository = ${{ github.repository }}
          echo github.repository_id = ${{ github.repository_id }}
          echo github.repositoryUrl = ${{ github.repositoryUrl }}
          echo github.run_attempt = ${{ github.run_attempt }}
          echo github.sha = ${{ github.sha }}
          echo github.triggering_actor = ${{ github.triggering_actor }}
        
          
          
          
