name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm 9
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup npmrc
        run: |
          echo @kurly-fe-labs:registry=https://npm.pkg.github.com  >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.TEST_ORG_1 }}" >> .npmrc

      - name: Install Dependencies
        run: pnpm i

      - name: Trigger build
        run: pnpm run build
