name: Deploy to Test Environment

on:
  push:
    branches:
      - ${{ vars.TEST_DEPLOY_BRANCH_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to test environment
        run: |
          echo "Deploying branch ${{ github.ref }} to test environment..."
